### ISSUE TITLE
beautiful soup deprecated

### ISSUE THREAD

**Issue by thetravellor** [halfordfan/check-mk-homeassistant#2]
Once you install beautiful soup4 the script will run, but the HA observer returns no data.

**Comment by halfordfan** [comment]
Are you seeing no data when you run it at the command line?  How is it configured in CheckMK?

**Comment by halfordfan** [comment]
`OMD[monitor]:~/local/bin$ ./check_haobserver.py homeassistant`
`<<<check_mk>>>`
`Version: 1.0`
`AgentOS: HomeAssistant`
`<<<local>>>`
`0 Supervisor connected=1 Supervisor reports Connected`
`0 Supported connected=1 Supported reports Supported`
`0 Healthy connected=1 Healthy reports Healthy`

Note that there is no checking on the name resolution of the host.  If it fails, the agent will not produce anything in the `local` section.

**Comment by halfordfan** [comment]
I think I have mitigated a potential failure scenario with the checkin for issue #3.  Let me know if you are still getting no output and we can debug further.
